export const 
environment = {
  production: false,

  //local
  // api_url : "http://localhost:8080/timesheet",
  // api_logincheck_url:"http://localhost:8080/timesheet/FirstUser/",
  // api_reset_url:"http://localhost:8080/timesheet/Forgotpass/",
  // api_otpcheck_url:"http://localhost:8080/timesheet/ChangePassword",
  // api_monthyear_url:"http://localhost:8080/timesheet/TimeSheetweekdays/",
  // api_projectlist_url:"http://localhost:8080/timesheet/ProjectList",
  // api_activitylist_url:"http://localhost:8080/timesheet/getActivityList/",
  // api_addtimesheet_url:"http://localhost:8080/timesheet/AddTimeSheet",
  // api_deleteTshtIds:"http://localhost:8080/timesheet/deleteTimeSheets",
  // api_url_owner:"http://localhost:8080/timesheet/UserList/false",
  // api_url_emp :"http://localhost:8080/timesheet/UserList/true",
  // api_url_editProject :"http://localhost:8080/timesheet/Project/Pro003",
  // api_weeklytimesheet_url :"http://localhost:8080/timesheet/getTimeSheetDetails_bsdon_emp/",
  // api_tshtsave_url :"http://localhost:8080/timesheet/AddTimeSheet",
  // api_tshtupdate_url :"http://localhost:8080/timesheet/TimeSheetUpdate",
  // api_tshtdownload_url :"http://localhost:8080/timesheet/download/",
  // api_dropdown_list_url : "http://localhost:8080/timesheet/masterdata",
  // api_country : "http://localhost:8080/timesheet/Country/",
  // api_state : "http://localhost:8080/timesheet/Country_State/",
  // api_city : "http://localhost:8080/timesheet/Country_State_City/",
  // api_url_apply_leave :"http://localhost:8080/timesheet/apply_timeoff",
  // api_url_get_leave :"http://localhost:8080/timesheet",
  // api_url_Post_leave :"http://localhost:8080/timesheet/a_r_RM_timeoff",
  // api_url_Post_leave_config : "http://localhost:8080/timesheet/leaveConfigurationHR",
  // api_url_Holiday : "http://localhost:8080/timesheet/addHolidays",
  // api_url_isValidProjectActivityDate:"http://localhost:8080/timesheet/isValidProjectActivityDate",
  // api_url_getAllocatedHours:"http://localhost:8080/timesheet/getAllocatedHours",
  // api_url_getProjectAllocatedHours:"http://localhost:8080/timesheet/projectHours",
  // api_url_validateResourceAllocatedHrs:"http://localhost:8080/timesheet/validateResourceAllocatedHrs",
  // api_url_validateResourceAllocateHrsOntime:"http://localhost:8080/timesheet/validateResourceAllocateHrsOntime"

  //Priyanka IP
  api_url : "http://localhost:8080/timesheet",
  api_logincheck_url:"http://localhost:8080/timesheet/FirstUser/",
  api_reset_url:"http://localhost:8080/timesheet/Forgotpass/",
  api_otpcheck_url:"http://localhost:8080/timesheet/ChangePassword",
  api_monthyear_url:"http://localhost:8080/timesheet/TimeSheetweekdays/",
  api_projectlist_url:"http://localhost:8080/timesheet/ProjectList",
  api_activitylist_url:"http://localhost:8080/timesheet/getActivityList/",
  api_addtimesheet_url:"http://localhost:8080/timesheet/AddTimeSheet",
  api_deleteTshtIds:"http://localhost:8080/timesheet/deleteTimeSheets",
  api_url_owner:"http://localhost:8080/timesheet/UserList/false",
  api_url_emp :"http://localhost:8080/timesheet/UserList/true",
  api_url_editProject :"http://localhost:8080/timesheet/Project/Pro003",
  api_weeklytimesheet_url :"http://localhost:8080/timesheet/getTimeSheetDetails_bsdon_emp/",
  api_tshtsave_url :"http://localhost:8080/timesheet/AddTimeSheet",
  api_tshtupdate_url :"http://localhost:8080/timesheet/TimeSheetUpdate",
  api_tshtdownload_url :"http://localhost:8080/timesheet/download/",
  api_dropdown_list_url : "http://localhost:8080/timesheet/masterdata",
  api_country : "http://localhost:8080/timesheet/Country/",
  api_state : "http://localhost:8080/timesheet/Country_State/",
  api_city : "http://localhost:8080/timesheet/Country_State_City/",
  api_url_apply_leave :"http://localhost:8080/timesheet/apply_timeoff",
  api_url_get_leave :"http://localhost:8080/timesheet",
  api_url_Post_leave :"http://localhost:8080/timesheet/a_r_RM_timeoff",
  api_url_Post_leave_config : "http://localhost:8080/timesheet/leaveConfigurationHR",
  api_url_Holiday : "http://localhost:8080/timesheet/addHolidays",
  api_url_isValidProjectActivityDate:"http://localhost:8080/timesheet/isValidProjectActivityDate",
  api_url_getAllocatedHours:"http://localhost:8080/timesheet/getAllocatedHours",
  api_url_getProjectAllocatedHours:"http://localhost:8080/timesheet/projectHours",
  api_url_validateResourceAllocatedHrs:"http://localhost:8080/timesheet/validateResourceAllocatedHrs",
  api_url_validateResourceAllocateHrsOntime:"http://localhost:8080/timesheet/validateResourceAllocateHrsOntime"

}

